### ISSUE TITLE
Add image to PostgresCluster.yaml that pulls from bcgov artifactory

### ISSUE THREAD

**Issue by pauldaustin** [bcgov/how-to-workshops#21]
I see in the following chat you are recommending getting images from the bcgov artifactory

https://chat.developer.gov.bc.ca/channel/crunchydb?msg=xeo4BowwnLySQmXRo

Could you update the README.md to that affect and add in a sample image into PostgresCluster.yaml?

**Comment by caggles** [comment]
This has been covered by PR #23
